# Generated by Django 6.0.2 on 2026-04-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Administrator'), ('Planning', 'Planning'), ('Marketing', 'Marketing'), ('Accounts', 'Accounts'), ('Procurement', 'Procurement'), ('Dispatch', 'Dispatch'), ('Management', 'Management'), ('Store', 'Store Manager'), ('Viewer', 'Viewer Only')], default='Viewer', max_length=20),
        ),
    ]
