# Generated by Django 6.0.2 on 2026-03-04 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0002_item_group1_name_item_section_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location_type', models.CharField(choices=[('STORE', 'Store'), ('FABRICATION', 'Fabrication Agency'), ('PAINTING', 'Painting Agency'), ('DISPATCH_SECTION', 'Dispatch Section'), ('TRUCK', 'Truck')], max_length=30)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('RAW', 'Raw Material'), ('OFFCUT', 'Offcut'), ('FINISHED_MARK', 'Finished Mark')], max_length=20)),
                ('qty', models.DecimalField(decimal_places=3, max_digits=12)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=12)),
                ('qr_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('mark_no', models.CharField(blank=True, max_length=100)),
                ('photo_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.item')),
            ],
        ),
        migrations.CreateModel(
            name='StockTxn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_type', models.CharField(choices=[('GRN_RAW', 'Raw Material Inward'), ('IN_OFFCUT', 'Offcut Inward'), ('ISSUE_FAB', 'Issue to Fabrication'), ('RETURN_FAB', 'Return from Fabrication'), ('ISSUE_PAINT', 'Issue to Painting'), ('RETURN_PAINT', 'Return from Painting'), ('DISPATCH', 'Dispatch')], max_length=30)),
                ('reference_no', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=12)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.item')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.stocklocation')),
                ('stock_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.stockobject')),
                ('txn', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.stocktxn')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockTxnLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=12)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=12)),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='from_location', to='ledger.stocklocation')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.item')),
                ('stock_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.stockobject')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='to_location', to='ledger.stocklocation')),
                ('txn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='ledger.stocktxn')),
            ],
        ),
    ]
