# Generated by Django 6.0.2 on 2026-03-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockobject',
            name='qr_required',
            field=models.BooleanField(default=False),
        ),
    ]
