# Generated by Django 6.0.2 on 2026-03-21 10:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_stockobject_qr_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockobject',
            name='capture_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='stockobject',
            name='capture_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='stockobject',
            name='qr_code',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='QR code must be exactly 16 digits.', regex='^\\d{16}$')]),
        ),
    ]
