# Generated by Django 6.0.2 on 2026-04-17 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_stockobject_capture_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklocation',
            name='bin_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='stocklocation',
            name='rack_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='stocklocation',
            name='remarks',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='stocklocation',
            name='shelf_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='stockobject',
            name='remarks',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='stockobject',
            name='source_type',
            field=models.CharField(choices=[('OPENING', 'Opening Stock'), ('NEW_PURCHASE', 'New Purchase Inward'), ('RETURN_FAB', 'Return from Fabrication'), ('RETURN_PAINT', 'Return from Painting'), ('CORRECTION', 'Correction Entry'), ('TEMP_RETURN', 'Temporary Return')], default='OPENING', max_length=30),
        ),
        migrations.AddField(
            model_name='stocktxn',
            name='bridge_status',
            field=models.CharField(choices=[('NOT_APPLICABLE', 'Not Applicable'), ('OPEN', 'Open'), ('PARTIALLY_RETURNED', 'Partially Returned'), ('RETURNED', 'Returned'), ('CONSUMED', 'Consumed'), ('PENDING_ERP_INTEGRATION', 'Pending ERP Integration'), ('INTEGRATED', 'Integrated')], default='NOT_APPLICABLE', max_length=30),
        ),
        migrations.AddField(
            model_name='stocktxn',
            name='entry_source_type',
            field=models.CharField(choices=[('OPENING', 'Opening Stock'), ('NEW_PURCHASE', 'New Purchase Inward'), ('RETURN', 'Return'), ('CORRECTION', 'Correction'), ('TEMPORARY', 'Temporary Bridge')], default='OPENING', max_length=30),
        ),
        migrations.AddField(
            model_name='stocktxn',
            name='integrated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocktxn',
            name='parent_txn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_transactions', to='ledger.stocktxn'),
        ),
        migrations.AddField(
            model_name='stocktxn',
            name='project_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='stocktxn',
            name='project_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='stocktxn',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='stockobject',
            name='object_type',
            field=models.CharField(choices=[('RAW', 'Raw Material'), ('OFFCUT', 'Offcut'), ('SCRAP', 'Scrap'), ('FINISHED_MARK', 'Finished Mark')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stocktxn',
            name='txn_type',
            field=models.CharField(choices=[('OPENING_RAW', 'Opening Raw Material Inward'), ('OPENING_OFFCUT', 'Opening Offcut Inward'), ('OPENING_SCRAP', 'Opening Scrap Inward'), ('GRN_RAW', 'Raw Material Inward'), ('IN_OFFCUT', 'Offcut Inward'), ('IN_SCRAP', 'Scrap Inward'), ('ISSUE_FAB', 'Issue to Fabrication'), ('RETURN_FAB', 'Return from Fabrication'), ('ISSUE_PAINT', 'Issue to Painting'), ('RETURN_PAINT', 'Return from Painting'), ('TEMP_ISSUE', 'Temporary Issue Pending ERP Integration'), ('TEMP_RETURN', 'Temporary Return Pending ERP Integration'), ('STOCK_CORRECTION', 'Stock Correction'), ('DISPATCH', 'Dispatch')], max_length=30),
        ),
    ]
