# Generated by Django 6.0.2 on 2026-04-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_stocklocation_bin_number_stocklocation_rack_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockobject',
            name='bin_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='stockobject',
            name='rack_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='stockobject',
            name='shelf_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
