# Generated by Django 6.0.2 on 2026-04-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0006_relax_qr_code_length_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockobject',
            name='rate_per_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
