# Generated by Django 6.0.2 on 2026-04-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0007_stockobject_rate_per_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockobject',
            name='heat_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='stockobject',
            name='plate_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='stockobject',
            name='test_certificate_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='stockobject',
            name='test_certificate_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
