# Generated by Django 6.0.2 on 2026-04-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0008_stockobject_heat_number_stockobject_plate_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockobject',
            name='test_certificate_file_unavailable',
            field=models.BooleanField(default=False),
        ),
    ]
