# Generated by Django 6.0.2 on 2026-03-02 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Groups 2',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('group2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='masters.group2')),
            ],
            options={
                'ordering': ['group2', 'code'],
                'unique_together': {('group2', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_master_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('item_description', models.TextField()),
                ('unit_weight', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('hsn_code', models.CharField(blank=True, max_length=20)),
                ('tax_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('import_batch_id', models.CharField(blank=True, max_length=50)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='masters.grade')),
                ('group2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='masters.group2')),
            ],
            options={
                'ordering': ['group2', 'grade', 'item_description'],
                'indexes': [models.Index(fields=['item_master_id'], name='masters_ite_item_ma_830c50_idx')],
            },
        ),
    ]
