# Generated by Django 6.0.2 on 2026-03-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='group1_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='item',
            name='section_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
