# Generated by Django 6.0.2 on 2026-03-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_item_group1_name_item_section_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_description_norm',
            field=models.CharField(blank=True, db_index=True, help_text='Auto-computed normalized description for matching and uniqueness. Not editable.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='unit_weight_basis',
            field=models.CharField(choices=[('KG_PER_M', 'kg per meter'), ('KG_PER_SQM', 'kg per square meter')], db_index=True, default='KG_PER_M', max_length=20),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['item_description_norm'], name='masters_ite_item_de_667c93_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['is_active'], name='masters_ite_is_acti_90b4c2_idx'),
        ),
    ]
