# Generated by Django 6.0.2 on 2026-04-01 07:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0003_item_item_description_norm_item_unit_weight_basis_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimateCostHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('line_type', models.CharField(choices=[('ENTRY', 'Entry'), ('TOTAL', 'Total')], default='ENTRY', max_length=20)),
                ('percentage', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('rate_per_kg', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=1)),
                ('is_percentage_editable', models.BooleanField(default=True)),
                ('is_rate_editable', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EstimateSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('contact_person', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EstimateBudgetHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_code', models.CharField(editable=False, max_length=120, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('budget_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('spent_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('approved_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cost_head', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_heads', to='estimation.estimatecosthead')),
            ],
            options={
                'ordering': ['budget_code'],
            },
        ),
        migrations.CreateModel(
            name='EstimateExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_date', models.DateField(default=django.utils.timezone.now)),
                ('reference_no', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_estimate_expenses', to=settings.AUTH_USER_MODEL)),
                ('budget_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='estimation.estimatebudgethead')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_estimate_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EstimateProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquiry_no', models.CharField(db_index=True, editable=False, max_length=30, unique=True)),
                ('client_name', models.CharField(max_length=255)),
                ('project_name', models.CharField(max_length=255)),
                ('quantity_mt', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('RATE_FINALIZATION', 'Rate Finalization'), ('QUOTATION_PENDING', 'Quotation Pending'), ('QUOTATION_FINALIZED', 'Quotation Finalized'), ('PO_RECEIVED', 'PO Received'), ('IN_EXECUTION', 'In Execution'), ('CLOSED', 'Closed')], db_index=True, default='DRAFT', max_length=30)),
                ('quotation_locked', models.BooleanField(default=False)),
                ('work_order_no', models.CharField(blank=True, max_length=100)),
                ('purchase_order_no', models.CharField(blank=True, max_length=100)),
                ('purchase_order_date', models.DateField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('raw_material_cost_per_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_estimated_cost_per_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quotation_price_per_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quotation_price_per_mt', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('quotation_value', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_estimate_projects', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_estimate_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', 'inquiry_no'],
            },
        ),
        migrations.AddField(
            model_name='estimatecosthead',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_heads', to='estimation.estimateproject'),
        ),
        migrations.AddField(
            model_name='estimatebudgethead',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_heads', to='estimation.estimateproject'),
        ),
        migrations.CreateModel(
            name='EstimateRawMaterialLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_mt', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('final_rate_per_mt', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('lowest_rate_per_mt', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('sort_order', models.PositiveIntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estimate_raw_material_lines', to='masters.item')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_material_lines', to='estimation.estimateproject')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='estimatecosthead',
            unique_together={('project', 'code')},
        ),
        migrations.CreateModel(
            name='EstimateRawMaterialRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_per_mt', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_rates', to='estimation.estimaterawmaterialline')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_material_rates', to='estimation.estimatesupplier')),
            ],
            options={
                'ordering': ['supplier__name'],
                'unique_together': {('line', 'supplier')},
            },
        ),
        migrations.CreateModel(
            name='EstimateProjectSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_order', models.PositiveIntegerField(default=1)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_suppliers', to='estimation.estimateproject')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_links', to='estimation.estimatesupplier')),
            ],
            options={
                'ordering': ['column_order', 'supplier__name'],
                'unique_together': {('project', 'supplier')},
            },
        ),
    ]
