# Generated by Django 6.0.2 on 2026-04-02 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_legacy_estimate_statuses(apps, schema_editor):
    EstimateProject = apps.get_model('estimation', 'EstimateProject')
    EstimateProject.objects.filter(status='QUOTATION_PENDING').update(status='UNDER_REVIEW')
    EstimateProject.objects.filter(status='QUOTATION_FINALIZED').update(status='APPROVED')


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0002_alter_estimatecosthead_percentage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='estimateproject',
            name='accounts_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='estimateproject',
            name='approved_price_per_mt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='estimateproject',
            name='decision_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estimateproject',
            name='decision_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decided_estimate_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estimateproject',
            name='decision_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='estimateproject',
            name='management_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='estimateproject',
            name='marketing_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='estimateproject',
            name='planning_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='estimateproject',
            name='quoted_price_per_mt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='estimateproject',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('RATE_FINALIZATION', 'Rate Finalization'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PO_RECEIVED', 'PO Received'), ('IN_EXECUTION', 'In Execution'), ('CLOSED', 'Closed')], db_index=True, default='DRAFT', max_length=30),
        ),
        migrations.RunPython(backfill_legacy_estimate_statuses, migrations.RunPython.noop),
    ]
