# Generated by Django 6.0.2 on 2026-03-10 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0001_initial'),
       ('procurement', '0006_fabricationjob_fabricationjobcomponent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drawingsheetrevision',
            options={'ordering': ['drawing_sheet', '-uploaded_at']},
        ),
        migrations.RenameField(
            model_name='drawingsheetrevision',
            old_name='sheet',
            new_name='drawing_sheet',
        ),
        migrations.RenameIndex(
            model_name='drawing',
            new_name='drawings_dr_drawing_207ecc_idx',
            old_name='drawings_dr_drawing_idx',
        ),
        migrations.RenameIndex(
            model_name='drawingsheet',
            new_name='drawings_dr_sheet_n_06a1d6_idx',
            old_name='drawings_dr_sheet_idx',
        ),
        migrations.RenameIndex(
            model_name='drawingsheetrevision',
            new_name='drawings_dr_is_curr_c6cacb_idx',
            old_name='drawings_dr_current_idx',
        ),
        migrations.RenameIndex(
            model_name='drawingsheetrevision',
            new_name='drawings_dr_revisio_5fa04d_idx',
            old_name='drawings_dr_revision_idx',
        ),
        migrations.AlterUniqueTogether(
            name='drawing',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='drawingsheet',
            name='description',
        ),
        migrations.AlterUniqueTogether(
            name='drawingsheetrevision',
            unique_together={('drawing_sheet', 'revision_no')},
        ),
        migrations.AddField(
            model_name='drawing',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_drawings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='drawing',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Temporary project link. Can later be replaced by a dedicated Project master.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='drawings', to='procurement.bomheader'),
        ),
        migrations.AddField(
            model_name='drawingsheetrevision',
            name='content_type',
            field=models.CharField(blank=True, default='application/pdf', max_length=100),
        ),
        migrations.AddField(
            model_name='drawingsheetrevision',
            name='file_key',
            field=models.CharField(default='', help_text='Cloudflare R2 object key', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drawingsheetrevision',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drawingsheetrevision',
            name='original_filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='drawingsheetrevision',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_drawing_revisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='drawingsheet',
            name='sheet_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='drawingsheetrevision',
            name='revision_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='drawing',
            unique_together={('project', 'drawing_no')},
        ),
        migrations.AlterModelTable(
            name='drawing',
            table=None,
        ),
        migrations.AlterModelTable(
            name='drawingsheet',
            table=None,
        ),
        migrations.AlterModelTable(
            name='drawingsheetrevision',
            table=None,
        ),
        migrations.RemoveField(
            model_name='drawingsheetrevision',
            name='file_path',
        ),
    ]
