# Generated by Django 6.0.2 on 2026-03-11 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0002_alter_drawingsheetrevision_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drawingsheet',
            options={'ordering': ['drawing', 'sheet_no'], 'verbose_name': 'Add Drawing Sheet', 'verbose_name_plural': 'Add Drawing Sheet'},
        ),
        migrations.AlterModelOptions(
            name='drawingsheetrevision',
            options={'ordering': ['drawing_sheet', '-uploaded_at'], 'verbose_name': 'Add Drawing Sheet Revision', 'verbose_name_plural': 'Add Drawing Sheet Revisions'},
        ),
    ]
