# Generated by Django 6.0.2 on 2026-03-11 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0003_alter_drawingsheet_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='drawingsheetrevision',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='drawingsheetrevision',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drawingsheetrevision',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_drawing_revisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='drawingsheetrevision',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
    ]
