# Generated by Django 6.0.2 on 2026-03-11 22:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0004_drawingsheetrevision_verification_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drawingsheet',
            options={'ordering': ['drawing', 'sheet_no'], 'verbose_name': 'Add Drawing Sheet', 'verbose_name_plural': 'Add Drawing Sheets'},
        ),
        migrations.AddIndex(
            model_name='drawingsheetrevision',
            index=models.Index(fields=['verification_status'], name='drawings_dr_verific_2b58c2_idx'),
        ),
    ]
