# Generated by Django 6.0.2 on 2026-03-13 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drawings", "0005_alter_drawingsheet_options_and_more"),
        ("procurement", "0009_add_production_status_to_bommark"),
    ]

    operations = [
        migrations.CreateModel(
            name='DrawingImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(blank=True, default='', max_length=255)),
                ('source_filename', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawing_import_batches', to='procurement.bomheader')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_drawing_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DrawingImportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('page_number', models.PositiveIntegerField(default=1)),
                ('detected_drawing_no', models.CharField(blank=True, default='', max_length=255)),
                ('detected_revision_no', models.CharField(blank=True, default='', max_length=50)),
                ('confirmed_drawing_no', models.CharField(blank=True, default='', max_length=255)),
                ('confirmed_revision_no', models.CharField(blank=True, default='', max_length=50)),
                ('extracted_text', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('ANALYZED', 'Analyzed'), ('NEEDS_REVIEW', 'Needs Review'), ('CONFIRMED', 'Confirmed'), ('SKIPPED', 'Skipped'), ('IMPORTED', 'Imported')], default='ANALYZED', max_length=20)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='drawings.drawingimportbatch')),
                ('imported_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_source_files', to='drawings.drawingsheetrevision')),
            ],
            options={
                'ordering': ['batch', 'page_number'],
            },
        ),
    ]
