# Generated by Django 6.0.2 on 2026-04-27 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0006_drawingimportbatch_drawingimportfile'),
        ('procurement', '0014_erc_bommark_erc_intercunit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawingimportbatch',
            name='bom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drawing_import_batches', to='procurement.bomheader'),
        ),
    ]
