# Generated by Django 6.0.2 on 2026-03-05 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_item_item_description_norm_item_unit_weight_basis_and_more'),
        ('procurement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BOMHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bom_name', models.CharField(max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_boms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='BOMMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(max_length=200)),
                ('mark_no', models.CharField(max_length=100)),
                ('drawing_no', models.CharField(blank=True, max_length=100, null=True)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='procurement.bomheader')),
            ],
            options={
                'ordering': ['mark_no'],
            },
        ),
        migrations.CreateModel(
            name='BOMComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.CharField(blank=True, max_length=20)),
                ('item_description_raw', models.CharField(max_length=255)),
                ('qty_all', models.DecimalField(decimal_places=3, max_digits=10)),
                ('length_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('line_weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('excel_row', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bom_components', to='masters.item')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='procurement.bommark')),
            ],
            options={
                'ordering': ['excel_row'],
            },
        ),
        migrations.AddIndex(
            model_name='bommark',
            index=models.Index(fields=['mark_no'], name='procurement_mark_no_48c40f_idx'),
        ),
    ]
