# Generated by Django 6.0.2 on 2026-03-08 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_bomheader_bommark_bomcomponent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bomheader',
            options={'ordering': ['-uploaded_at', 'bom_name']},
        ),
        migrations.AlterModelOptions(
            name='bommark',
            options={'ordering': ['sheet_name', 'mark_no']},
        ),
        migrations.AddField(
            model_name='bomheader',
            name='client_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='bomheader',
            name='project_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='bomheader',
            name='purchase_order_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bomheader',
            name='purchase_order_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bommark',
            name='area_of_supply',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bommark',
            name='revision_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bomheader',
            name='bom_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bomheader',
            name='uploaded_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='bomheader',
            name='uploaded_by',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='uploaded_boms',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name='bommark',
            index=models.Index(fields=['sheet_name', 'mark_no'], name='procurement_sheet_n_4d86df_idx'),
        ),
    ]
