# Generated by Django 6.0.2 on 2026-03-08 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_item_item_description_norm_item_unit_weight_basis_and_more'),
        ('procurement', '0004_remove_bomcomponent_qty_all_remove_bomheader_notes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bommark',
            options={'ordering': ['sheet_name', 'erc_mark']},
        ),
        
        migrations.RenameField(
            model_name='bomcomponent',
            old_name='mark',
            new_name='bom_mark',
        ),
        migrations.RenameField(
            model_name='bomcomponent',
            old_name='line_weight_kg',
            new_name='engg_weight_kg',
        ),
        migrations.RenameField(
            model_name='bomcomponent',
            old_name='grade_raw',
            new_name='grade_name',
        ),
        migrations.RenameField(
            model_name='bommark',
            old_name='mark_no',
            new_name='erc_mark',
        ),
        migrations.RemoveField(
            model_name='bomcomponent',
            name='item_no',
        ),
        migrations.RemoveField(
            model_name='bomcomponent',
            name='item_part_quantity',
        ),
        migrations.RemoveField(
            model_name='bomcomponent',
            name='qty_all',
        ),
        migrations.RemoveField(
            model_name='bomheader',
            name='notes',
        ),
        migrations.AddField(
            model_name='bomcomponent',
            name='part_mark',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bomcomponent',
            name='part_quantity_per_assy',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
        ),
        migrations.AddField(
            model_name='bomcomponent',
            name='section_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='bommark',
            name='erc_quantity',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
        ),
        migrations.AddField(
            model_name='bommark',
            name='main_section',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='bomcomponent',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bom_components', to='masters.item'),
        ),
        migrations.AlterField(
            model_name='bomcomponent',
            name='item_description_raw',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='bommark',
            index=models.Index(fields=['erc_mark'], name='procurement_erc_mar_2f6d90_idx'),
        ),
        migrations.AddIndex(
            model_name='bommark',
            index=models.Index(fields=['sheet_name', 'erc_mark'], name='procurement_sheet_n_5bc53f_idx'),
        ),
    ]
