C4# Generated by Django 6.0.2 on 2026-03-08 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_item_item_description_norm_item_unit_weight_basis_and_more'),
        ('procurement', '0005_alter_bommark_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FabricationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_mark', models.CharField(max_length=120, unique=True)),
                ('job_sequence', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('HOLD', 'Hold')], default='OPEN', max_length=20)),
            ],
            options={
                'ordering': ['job_mark'],
            },
        ),
        migrations.CreateModel(
            name='FabricationJobComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_mark', models.CharField(blank=True, max_length=100)),
                ('section_name', models.CharField(blank=True, default='', max_length=255)),
                ('grade_name', models.CharField(blank=True, max_length=255)),
                ('part_quantity', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('length_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('width_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('engg_weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
       
        migrations.AddField(
            model_name='fabricationjob',
            name='bom_mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fabrication_jobs', to='procurement.bommark'),
        ),
        migrations.AddField(
            model_name='fabricationjobcomponent',
            name='fabrication_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='procurement.fabricationjob'),
        ),
        migrations.AddField(
            model_name='fabricationjobcomponent',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fabrication_job_components', to='masters.item'),
        ),
        migrations.AddIndex(
            model_name='fabricationjob',
            index=models.Index(fields=['job_mark'], name='procurement_job_mar_3b9e94_idx'),
        ),
        migrations.AddIndex(
            model_name='fabricationjob',
            index=models.Index(fields=['bom_mark', 'job_sequence'], name='procurement_bom_mar_dfc6be_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fabricationjob',
            unique_together={('bom_mark', 'job_sequence')},
        ),
    ]
