# Generated by Django 6.0.2 on 2026-03-11 15:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0006_fabricationjob_fabricationjobcomponent_and_more'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='bomheader',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bomheader',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bomheader',
            name='order_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='bomheader',
            name='order_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='bomheader',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
