# Generated by Django 6.0.2 on 2026-03-08 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0006_fabricationjob_fabricationjobcomponent_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bommark',
            name='procurement_mark_no_48c40f_idx',
        ),
        migrations.RemoveIndex(
            model_name='bommark',
            name='procurement_sheet_n_4d86df_idx',
        ),
        migrations.AddField(
            model_name='bomheader',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bomheader',
            name='locked_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
