# Generated by Django

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0005_alter_drawingsheet_options_and_more'),
        ('procurement', '0007_remove_bommark_procurement_mark_no_48c40f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bommark',
            name='drawing',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='bom_marks',
                to='drawings.drawing',
            ),
        ),
    ]