# Generated by Django 6.0.2 on 2026-03-21 10:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0010_bomcolumnmapping'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bommark',
            name='procurement_mark_no_48c40f_idx',
        ),
        migrations.RemoveIndex(
            model_name='bommark',
            name='procurement_sheet_n_4d86df_idx',
        ),
        migrations.AddIndex(
            model_name='bomcolumnmapping',
            index=models.Index(fields=['sheet_name', 'header_signature'], name='procurement_sheet_n_1832c3_idx'),
        ),
    ]
