# Generated by Django 6.0.2 on 2026-03-21 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0011_remove_bommark_procurement_mark_no_48c40f_idx_and_more'),
    ]

    operations = []
