# Generated by Django 6.0.2 on 2026-04-01 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0001_initial'),
        ('procurement', '0012_remove_bommark_procurement_mark_no_48c40f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomheader',
            name='estimate_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boms', to='estimation.estimateproject'),
        ),
    ]
