# Generated by Django 6.0.2 on 2026-04-25 02:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0006_drawingimportbatch_drawingimportfile'),
        ('estimation', '0008_convert_units_to_kg'),
        ('masters', '0003_item_item_description_norm_item_unit_weight_basis_and_more'),
        ('procurement', '0013_bomheader_estimate_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ERC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(max_length=200)),
                ('erc_mark', models.CharField(max_length=100)),
                ('erc_quantity', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('drawing_no', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('MATERIAL_EVALUATED', 'Material Evaluated'), ('RELEASED_TO_PRODUCTION', 'Released to Production'), ('DISPATCHED', 'Dispatched')], default='PLANNED', max_length=40)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bom_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ercs', to='procurement.bomheader')),
                ('drawing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ercs', to='drawings.drawing')),
            ],
            options={
                'ordering': ['work_order__wo_number', 'sheet_name', 'erc_mark'],
            },
        ),
        migrations.AddField(
            model_name='bommark',
            name='erc',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bom_mark', to='procurement.erc'),
        ),
        migrations.CreateModel(
            name='INTERCUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_erc_code', models.CharField(max_length=140, unique=True)),
                ('sequence', models.PositiveIntegerField()),
                ('dispatch_state', models.CharField(choices=[('NOT_DISPATCHED', 'Not Dispatched'), ('DISPATCHED', 'Dispatched')], default='NOT_DISPATCHED', max_length=20)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('MATERIAL_EVALUATED', 'Material Evaluated'), ('RELEASED_TO_PRODUCTION', 'Released to Production'), ('ISSUED', 'Issued'), ('IN_FABRICATION', 'In Fabrication'), ('FABRICATION_COMPLETE', 'Fabrication Complete'), ('OFFERED_TO_QC', 'Offered to QC'), ('QC_ACCEPTED', 'QC Accepted'), ('PAINT_QC_ACCEPTED', 'Paint QC Accepted'), ('READY_FOR_DISPATCH', 'Ready for Dispatch'), ('DISPATCHED', 'Dispatched')], default='PLANNED', max_length=40)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('erc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='int_units', to='procurement.erc')),
            ],
            options={
                'ordering': ['int_erc_code'],
            },
        ),
        migrations.AddField(
            model_name='fabricationjob',
            name='int_erc_unit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_fabrication_job', to='procurement.intercunit'),
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wo_number', models.CharField(max_length=100, unique=True)),
                ('project_name', models.CharField(blank=True, max_length=255)),
                ('client_name', models.CharField(blank=True, max_length=255)),
                ('purchase_order_no', models.CharField(blank=True, max_length=100)),
                ('purchase_order_date', models.DateField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('order_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('order_value', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('MATERIAL_EVALUATED', 'Material Evaluated'), ('RELEASED_TO_PRODUCTION', 'Released to Production'), ('CLOSED', 'Closed')], default='PLANNED', max_length=40)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_work_orders', to=settings.AUTH_USER_MODEL)),
                ('estimate_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='estimation.estimateproject')),
            ],
            options={
                'ordering': ['-created_at', 'wo_number'],
            },
        ),
        migrations.CreateModel(
            name='RequirementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_specification', models.CharField(max_length=255)),
                ('grade_name', models.CharField(blank=True, max_length=255)),
                ('part_mark', models.CharField(blank=True, max_length=100)),
                ('required_qty', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('required_weight_kg', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('covered_qty', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('covered_weight_kg', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('is_fully_covered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bom_component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirement_lines', to='procurement.bomcomponent')),
                ('erc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_lines', to='procurement.erc')),
                ('int_erc_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_lines', to='procurement.intercunit')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requirement_lines', to='masters.item')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_lines', to='procurement.workorder')),
            ],
            options={
                'ordering': ['int_erc_unit__int_erc_code', 'item_specification', 'part_mark'],
            },
        ),
        migrations.AddField(
            model_name='intercunit',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='int_erc_units', to='procurement.workorder'),
        ),
        migrations.AddField(
            model_name='erc',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ercs', to='procurement.workorder'),
        ),
        migrations.AddField(
            model_name='bomheader',
            name='work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='boms', to='procurement.workorder'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['wo_number'], name='procurement_wo_numb_9d1a9d_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['status'], name='procurement_status_08e6d4_idx'),
        ),
        migrations.AddIndex(
            model_name='requirementline',
            index=models.Index(fields=['work_order', 'item'], name='procurement_work_or_2aa84a_idx'),
        ),
        migrations.AddIndex(
            model_name='requirementline',
            index=models.Index(fields=['is_fully_covered'], name='procurement_is_full_24a2b6_idx'),
        ),
        migrations.AddIndex(
            model_name='intercunit',
            index=models.Index(fields=['int_erc_code'], name='procurement_int_erc_abec2e_idx'),
        ),
        migrations.AddIndex(
            model_name='intercunit',
            index=models.Index(fields=['dispatch_state'], name='procurement_dispatc_6adb22_idx'),
        ),
        migrations.AddIndex(
            model_name='intercunit',
            index=models.Index(fields=['status'], name='procurement_status_97c30a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='intercunit',
            unique_together={('erc', 'sequence')},
        ),
        migrations.AddIndex(
            model_name='erc',
            index=models.Index(fields=['erc_mark'], name='procurement_erc_mar_120947_idx'),
        ),
        migrations.AddIndex(
            model_name='erc',
            index=models.Index(fields=['status'], name='procurement_status_84e63a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='erc',
            unique_together={('work_order', 'sheet_name', 'erc_mark', 'drawing_no')},
        ),
    ]
